import * as SQLite from 'expo-sqlite';
import type {Bill,Floor,Room,Tenant} from '../types';
import {makeId,now} from '../lib/id';
let db:SQLite.SQLiteDatabase;
let dbScope='';
export async function initDb(userId='preview'){const scope=userId.replace(/[^a-zA-Z0-9-]/g,'');if(db&&dbScope===scope)return;if(db)await db.closeAsync();dbScope=scope;db=await SQLite.openDatabaseAsync(`house-rent-manager-${scope}.db`);await db.execAsync(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS floors(id TEXT PRIMARY KEY,name TEXT NOT NULL,address TEXT NOT NULL DEFAULT '',photo_uri TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,sync_status TEXT NOT NULL DEFAULT 'pending');
CREATE TABLE IF NOT EXISTS rooms(id TEXT PRIMARY KEY,floor_id TEXT NOT NULL,room_number TEXT NOT NULL,monthly_rent REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'vacant',photo_uri TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,sync_status TEXT NOT NULL DEFAULT 'pending',FOREIGN KEY(floor_id) REFERENCES floors(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS tenants(id TEXT PRIMARY KEY,room_id TEXT NOT NULL,full_name TEXT NOT NULL,phone TEXT NOT NULL,email TEXT,id_type TEXT NOT NULL,id_number TEXT NOT NULL,move_in_date TEXT NOT NULL,monthly_rent REAL NOT NULL,photo_uri TEXT,notes TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,sync_status TEXT NOT NULL DEFAULT 'pending',FOREIGN KEY(room_id) REFERENCES rooms(id));
CREATE TABLE IF NOT EXISTS documents(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,document_type TEXT NOT NULL,local_uri TEXT NOT NULL,remote_path TEXT,file_name TEXT NOT NULL,mime_type TEXT,created_at TEXT NOT NULL,sync_status TEXT NOT NULL DEFAULT 'pending',FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS bills(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,bill_month TEXT NOT NULL,rent REAL NOT NULL,electricity REAL NOT NULL DEFAULT 0,water REAL NOT NULL DEFAULT 0,waste REAL NOT NULL DEFAULT 0,additional REAL NOT NULL DEFAULT 0,previous_due REAL NOT NULL DEFAULT 0,advance_used REAL NOT NULL DEFAULT 0,paid_amount REAL NOT NULL DEFAULT 0,total REAL NOT NULL,balance REAL NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,sync_status TEXT NOT NULL DEFAULT 'pending',FOREIGN KEY(tenant_id) REFERENCES tenants(id),UNIQUE(tenant_id,bill_month));
CREATE TABLE IF NOT EXISTS sync_queue(id INTEGER PRIMARY KEY AUTOINCREMENT,entity TEXT NOT NULL,entity_id TEXT NOT NULL,operation TEXT NOT NULL,payload TEXT NOT NULL,created_at TEXT NOT NULL,retry_count INTEGER NOT NULL DEFAULT 0);`);}
const queue=async(entity:string,id:string,payload:unknown)=>db.runAsync('INSERT INTO sync_queue(entity,entity_id,operation,payload,created_at) VALUES(?,?,?,?,?)',entity,id,'upsert',JSON.stringify(payload),now());
export const listFloors=()=>db.getAllAsync<Floor>('SELECT * FROM floors ORDER BY name');
export const listRooms=()=>db.getAllAsync<Room>('SELECT * FROM rooms ORDER BY room_number');
export const listTenants=()=>db.getAllAsync<Tenant>('SELECT * FROM tenants ORDER BY full_name');
export const listBills=()=>db.getAllAsync<Bill>('SELECT * FROM bills ORDER BY bill_month DESC,created_at DESC');
export async function addFloor(name:string,address:string,photo_uri?:string){const x={id:makeId(),name,address,photo_uri:photo_uri??null,created_at:now(),updated_at:now(),sync_status:'pending'};await db.runAsync('INSERT INTO floors VALUES(?,?,?,?,?,?,?)',...Object.values(x));await queue('floors',x.id,x);return x;}
export async function addRoom(v:{floor_id:string;room_number:string;monthly_rent:number;photo_uri?:string}){const x={id:makeId(),...v,status:'vacant',photo_uri:v.photo_uri??null,created_at:now(),updated_at:now(),sync_status:'pending'};await db.runAsync('INSERT INTO rooms VALUES(?,?,?,?,?,?,?,?,?)',x.id,x.floor_id,x.room_number,x.monthly_rent,x.status,x.photo_uri,x.created_at,x.updated_at,x.sync_status);await queue('rooms',x.id,x);return x;}
export async function addTenant(v:{room_id:string;full_name:string;phone:string;email?:string;id_type:string;id_number:string;move_in_date:string;monthly_rent:number;photo_uri?:string;notes?:string}){const x={id:makeId(),...v,email:v.email??null,photo_uri:v.photo_uri??null,notes:v.notes??null,created_at:now(),updated_at:now(),sync_status:'pending'};await db.runAsync('INSERT INTO tenants VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',x.id,x.room_id,x.full_name,x.phone,x.email,x.id_type,x.id_number,x.move_in_date,x.monthly_rent,x.photo_uri,x.notes,x.created_at,x.updated_at,x.sync_status);await db.runAsync("UPDATE rooms SET status='occupied',updated_at=?,sync_status='pending' WHERE id=?",now(),x.room_id);await queue('tenants',x.id,x);return x;}
export async function addDocument(v:{tenant_id:string;document_type:string;local_uri:string;file_name:string;mime_type?:string}){const x={id:makeId(),...v,remote_path:null,created_at:now(),sync_status:'pending'};await db.runAsync('INSERT INTO documents VALUES(?,?,?,?,?,?,?,?,?)',x.id,x.tenant_id,x.document_type,x.local_uri,x.remote_path,x.file_name,x.mime_type??null,x.created_at,x.sync_status);await queue('documents',x.id,x);}
export async function addBill(v:Omit<Bill,'id'|'total'|'balance'|'status'|'created_at'|'updated_at'|'sync_status'>){const total=v.rent+v.electricity+v.water+v.waste+v.additional+v.previous_due-v.advance_used;const balance=Math.max(0,total-v.paid_amount);const status:Bill['status']=balance===0?'paid':v.paid_amount>0?'partial':'due';const x={id:makeId(),...v,total,balance,status,created_at:now(),updated_at:now(),sync_status:'pending'};await db.runAsync('INSERT INTO bills VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',x.id,x.tenant_id,x.bill_month,x.rent,x.electricity,x.water,x.waste,x.additional,x.previous_due,x.advance_used,x.paid_amount,x.total,x.balance,x.status,x.created_at,x.updated_at,x.sync_status);await queue('bills',x.id,x);return x;}
export const getQueue=()=>db.getAllAsync<any>('SELECT * FROM sync_queue ORDER BY id LIMIT 100');
export const markSynced=async(entity:string,entityId:string,queueId:number)=>{await db.runAsync(`UPDATE ${entity} SET sync_status='synced' WHERE id=?`,entityId);await db.runAsync('DELETE FROM sync_queue WHERE id=?',queueId);};
export async function replaceFromCloud(data:{floors:any[];rooms:any[];tenants:any[];documents:any[];bills:any[]}){await db.withTransactionAsync(async()=>{await db.execAsync('DELETE FROM bills;DELETE FROM documents;DELETE FROM tenants;DELETE FROM rooms;DELETE FROM floors;');for(const x of data.floors)await db.runAsync('INSERT INTO floors VALUES(?,?,?,?,?,?,?)',x.id,x.name,x.address,x.photo_uri,x.created_at,x.updated_at,'synced');for(const x of data.rooms)await db.runAsync('INSERT INTO rooms VALUES(?,?,?,?,?,?,?,?,?)',x.id,x.floor_id,x.room_number,x.monthly_rent,x.status,x.photo_uri,x.created_at,x.updated_at,'synced');for(const x of data.tenants)await db.runAsync('INSERT INTO tenants VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',x.id,x.room_id,x.full_name,x.phone,x.email,x.id_type,x.id_number,x.move_in_date,x.monthly_rent,x.photo_uri,x.notes,x.created_at,x.updated_at,'synced');for(const x of data.documents)await db.runAsync('INSERT INTO documents VALUES(?,?,?,?,?,?,?,?,?)',x.id,x.tenant_id,x.document_type,'',x.remote_path,x.file_name,x.mime_type,x.created_at,'synced');for(const x of data.bills)await db.runAsync('INSERT INTO bills VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',x.id,x.tenant_id,x.bill_month,x.rent,x.electricity,x.water,x.waste,x.additional,x.previous_due,x.advance_used,x.paid_amount,x.total,x.balance,x.status,x.created_at,x.updated_at,'synced');});}
